//go:build ignore

package main

import (
	"log"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g" IOProfiler ../ebpf/src/io_profiler.bpf.c

func main() {
	// Generate BPF objects
	if err := generateBPFObjects(); err != nil {
		log.Fatalf("Failed to generate BPF objects: %v", err)
	}
}

func generateBPFObjects() error {
	// This will be generated by bpf2go
	return nil
}
