name: CI

on:
  push:
    branches:
      - main
      - master
      - '**'   # all branches
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op step
        run: echo "CI is set up. No checks yet."